---
name: OpenWisp2 Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Python==3.7
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Upgrade python system packages
        run: pip install -U "pip==20.2.4" wheel

      - name: Install test dependencies
        run: |
          pip install -U -r requirements.txt
          pip install pylinkvalidator

      - name: Install npm dependencies
        run: sudo npm install -g stylelint

      - name: QA checks
        run: ./run-qa-checks

      - name: Setup Google Cloud
        if: ${{ github.event_name=='push' }}
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_DOWNLOADS_SERVICE_ACCOUNT_JSON }}
          project_id: ${{ secrets.GCS_PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy pages to openwisp.io/docs
        if: ${{ github.event_name=='push' }}
        run: gsutil -m rsync -r ${{ env.SRC_URL }}/_build/html ${{ env.DST_URL }}
        env:
          SRC_URL: /home/runner/work/openwisp2-docs/openwisp2-docs
          DST_URL: gs://${{ secrets.GCS_DOCS_BUCKET_NAME }}/docs
